name: CI

on:
  push:
    branches: [main, '**']
  pull_request:

jobs:
  build-python-package:
    name: Build python package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          pip install -r requirements-dev.txt

      - name: Build package
        run: python -m build

      - name: Check distributions
        run:
          twine check dist/*

      - name: Upload package artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: docker buildx setup
      uses: docker/setup-buildx-action@v3.10.0

    - name: Build the docker image
      run: RELEASE_BUILD=false /bin/bash ./docker/build.sh ${GITHUB_SHA:0:8}

    - name: Clean up
      run: |
        docker logout

  tag-version-if-needed:
    name: Tag new version if needed
    runs-on: ubuntu-latest
    needs: [build-python-package, build-docker-image]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all tags
      - name: Skip job if VERSION not changed
        run: |
          if ! git diff --name-only HEAD~1 | grep -q '^VERSION$'; then
            echo "VERSION file not changed, skipping tagging."
            exit 0
          fi
      - name: Read version from VERSION file
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG"
          git push origin "$TAG"
        